### ISSUE TITLE
npm start not working correctoly

### ISSUE THREAD

**Issue by akm12109** [raj074/mern-social-media#18]
@akm12109 ➜ /workspaces/mern-social-media (master) $ node server
/workspaces/mern-social-media/node_modules/mongoose/lib/connection.js:694
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (/workspaces/mern-social-media/node_modules/mongoose/lib/connection.js:694:11)
    at /workspaces/mern-social-media/node_modules/mongoose/lib/index.js:351:10
    at promiseOrCallback (/workspaces/mern-social-media/node_modules/mongoose/lib/helpers/promiseOrCallback.js:10:12)
    at Mongoose._promiseOrCallback (/workspaces/mern-social-media/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/workspaces/mern-social-media/node_modules/mongoose/lib/index.js:350:20)
    at Object.<anonymous> (/workspaces/mern-social-media/server.js:45:10)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0
@akm12109 ➜ /workspaces/mern-social-media (master) $

**Comment by Pavanshah0804** [comment]
@akm12109 check your connection of MongoDB Connection and .env file.
Things to include in .env file 
->MONGODB_URI = "//<username>:<password>@cluster0.4737qev.mongodb.net/?retryWrites=true&w=majority" 

Don't forget to remove "<>".
